/**
 * Pull the live catalogue from the WooCommerce Store API and bake it into
 * src/data/woo.js.
 *
 * The Store API is public and needs no credentials, but WordPress.com does not
 * send `access-control-allow-origin`, so a browser cannot read it cross-origin.
 * Syncing at build time sidesteps that entirely: no key in the bundle, no
 * runtime dependency on the shop being up, and the storefront can be hosted
 * anywhere. Re-run whenever prices or stock change.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const STORE = process.env.WOO_STORE || 'https://vitalsuplementos.com.mx';
const here = dirname(fileURLToPath(import.meta.url));

// The live products were imported from the supplier, so their SKUs and names
// are the supplier's. This maps them onto our own catalogue slugs.
const BY_ID = {
  103: 'parches-ojeras',
  98: 'serum-4en1',
  91: 'creatina',
  86: 'mentas-cafeina',
  81: 'bloom-mango',
  75: 'joint-support',
  71: 'glutation-gomas',
  67: 'magnesio-180',
  58: 'tocobo-barra',
  53: 'nad-mens',
  46: 'medicube-colageno',
  41: 'crema-chillab',
  35: 'serum-anua',
  30: 'gel-salicilico',
  21: 'holy-basil',
  17: 'magnesio-cup'
};

const res = await fetch(`${STORE}/wp-json/wc/store/v1/products?per_page=100`, {
  headers: { Accept: 'application/json' }
});
if (!res.ok) throw new Error(`Store API ${res.status} ${res.statusText}`);
const live = await res.json();

const money = (minor, unit) => Math.round(Number(minor) / 10 ** unit);

const out = {};
const unmapped = [];
for (const p of live) {
  const slug = BY_ID[p.id];
  if (!slug) {
    unmapped.push(`${p.id} ${p.name}`);
    continue;
  }
  const u = p.prices.currency_minor_unit;
  const regular = money(p.prices.regular_price, u);
  const price = money(p.prices.price, u);
  out[slug] = {
    id: p.id,
    sku: p.sku || null,
    name: p.name,
    permalink: p.permalink,
    price,
    // only record a strike-through when the shop is actually running a sale
    was: p.on_sale && regular > price ? regular : 0,
    inStock: p.is_in_stock !== false,
    currency: p.prices.currency_code
  };
}

const missing = Object.values(BY_ID).filter((s) => !out[s]);
const payload = { store: STORE, syncedAt: new Date().toISOString(), products: out };
writeFileSync(
  join(here, '..', 'src', 'data', 'woo.js'),
  '// GENERATED by scripts/sync-woo.mjs — do not edit. Re-run `npm run sync:woo`.\n' +
    'export default ' + JSON.stringify(payload, null, 1) + ';\n'
);

console.log(`${Object.keys(out).length}/${live.length} products mapped from ${STORE}`);
if (unmapped.length) console.log('  unmapped in shop:', unmapped.join(', '));
if (missing.length) console.log('  expected but absent:', missing.join(', '));
